.TH al_acknowledge_resize 3 "" "Allegro reference manual"
.SH NAME
.PP
al_acknowledge_resize - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

bool\ al_acknowledge_resize(ALLEGRO_DISPLAY\ *display)
\f[]
.fi
.SH DESCRIPTION
.PP
When the user receives a resize event from a resizable display, if they
wish the display to be resized they must call this function to let the
graphics driver know that it can now resize the display.
Returns true on success.
.PP
Adjusts the clipping rectangle to the full size of the backbuffer.
.PP
Note that a resize event may be outdated by the time you acknowledge it;
there could be further resize events generated in the meantime.
.SH SEE ALSO
.PP
al_resize_display(3), ALLEGRO_EVENT(3)
