.TH al_color_html 3 "" "Allegro reference manual"
.SH NAME
.PP
al_color_html - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_color.h>

ALLEGRO_COLOR\ al_color_html(char\ const\ *string)
\f[]
.fi
.SH DESCRIPTION
.PP
Interprets an HTML styled hex number (e.g.
#00faff) as a color.
Components that are malformed are set to 0.
.SH SEE ALSO
.PP
al_color_html_to_rgb(3), al_color_rgb_to_html(3)
