.TH al_clone_bitmap 3 "" "Allegro reference manual"
.SH NAME
.PP
al_clone_bitmap - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

ALLEGRO_BITMAP\ *al_clone_bitmap(ALLEGRO_BITMAP\ *bitmap)
\f[]
.fi
.SH DESCRIPTION
.PP
Create a new bitmap with al_create_bitmap(3), and copy the pixel data
from the old bitmap across.
.SH SEE ALSO
.PP
al_create_bitmap(3), al_set_new_bitmap_format(3),
al_set_new_bitmap_flags(3)
