.TH al_cstr_dup 3 "" "Allegro reference manual"
.SH NAME
.PP
al_cstr_dup - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

char\ *al_cstr_dup(const\ ALLEGRO_USTR\ *us)
\f[]
.fi
.SH DESCRIPTION
.PP
Create a NUL (\[aq]\[aq]) terminated copy of the string.
Any embedded NUL bytes will still be presented in the returned string.
The new string must eventually be freed with al_free(3).
If an error occurs NULL is returned.
.SH SEE ALSO
.PP
al_cstr(3), al_ustr_to_buffer(3)
