.TH al_ferror 3 "" "Allegro reference manual"
.SH NAME
.PP
al_ferror - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

bool\ al_ferror(ALLEGRO_FILE\ *f)
\f[]
.fi
.SH DESCRIPTION
.PP
Returns true if the error indicator is set on the given file, i.e.
there was some sort of previous error.
.SH SEE ALSO
.PP
al_feof(3), al_fclearerr(3)
