.TH al_get_sample_instance_playing 3 "" "Allegro reference manual"
.SH NAME
.PP
al_get_sample_instance_playing - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_audio.h>

bool\ al_get_sample_instance_playing(const\ ALLEGRO_SAMPLE_INSTANCE\ *spl)
\f[]
.fi
.SH DESCRIPTION
.PP
Return true if the sample instance is playing.
.SH SEE ALSO
.PP
al_set_sample_instance_playing(3)
