.TH al_get_fs_entry_name 3 "" "Allegro reference manual"
.SH NAME
.PP
al_get_fs_entry_name - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

const\ char\ *al_get_fs_entry_name(ALLEGRO_FS_ENTRY\ *e)
\f[]
.fi
.SH DESCRIPTION
.PP
Returns the entry\[aq]s filename path.
Note that the path will not be an absolute path if the entry wasn\[aq]t
created from an absolute path.
Also note that the filesystem encoding may not be known and the
conversion to UTF-8 could in very rare cases cause this to return an
invalid path.
Therefore it\[aq]s always safest to access the file over its
ALLEGRO_FS_ENTRY(3) and not the path.
.PP
On success returns a read only string which you must not modify or
destroy.
Returns NULL on failure.
