.TH al_get_sample 3 "" "Allegro reference manual"
.SH NAME
.PP
al_get_sample - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_audio.h>

ALLEGRO_SAMPLE\ *al_get_sample(ALLEGRO_SAMPLE_INSTANCE\ *spl)
\f[]
.fi
.SH DESCRIPTION
.PP
Return the sample data that the sample instance plays.
.PP
Note this returns a pointer to an internal structure, \f[I]not\f[] the
ALLEGRO_SAMPLE(3) that you may have passed to al_set_sample(3).
You may, however, check which sample buffer is being played by the
sample instance with al_get_sample_data(3), and so on.
.SH SEE ALSO
.PP
al_set_sample(3)
