.TH al_get_native_file_dialog_path 3 "" "Allegro reference manual"
.SH NAME
.PP
al_get_native_file_dialog_path - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_native_dialog.h>

const\ char\ *al_get_native_file_dialog_path(
\ \ \ const\ ALLEGRO_FILECHOOSER\ *dialog,\ size_t\ i)
\f[]
.fi
.SH DESCRIPTION
.PP
Returns one of the selected paths.
