.TH al_get_mouse_event_source 3 "" "Allegro reference manual"
.SH NAME
.PP
al_get_mouse_event_source - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

ALLEGRO_EVENT_SOURCE\ *al_get_mouse_event_source(void)
\f[]
.fi
.SH DESCRIPTION
.PP
Retrieve the mouse event source.
.PP
Returns NULL if the mouse subsystem was not installed.
