.TH al_iphone_program_has_halted 3 "" "Allegro reference manual"
.SH NAME
.PP
al_iphone_program_has_halted - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_iphone.h>

void\ al_iphone_program_has_halted(void)
\f[]
.fi
.SH DESCRIPTION
.PP
Multitasking on iOS is different than on other platforms.
When an application receives an ALLEGRO_DISPLAY_SWITCH_OUT or
ALLEGRO_DISPLAY_CLOSE event on a multitasking-capable device, it should
cease all activity and do nothing but check for an
ALLEGRO_DISPLAY_SWITCH_IN event.
To let the iPhone driver know that you\[aq]ve ceased all activity, call
this function.
You should call this function very soon after receiving the event
telling you it\[aq]s time to switch out (within a couple milliseconds).
Certain operations, if done, will crash the program after this call,
most notably any function which uses OpenGL.
This function is needed because the "switch out" handler on iPhone
can\[aq]t return until these operations have stopped, or a crash as
described before can happen.
