.TH al_set_keyboard_leds 3 "" "Allegro reference manual"
.SH NAME
.PP
al_set_keyboard_leds - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

bool\ al_set_keyboard_leds(int\ leds)
\f[]
.fi
.SH DESCRIPTION
.PP
Overrides the state of the keyboard LED indicators.
Set to -1 to return to default behavior.
False is returned if the current keyboard driver cannot set LED
indicators.
