.TH ALLEGRO_DISPLAY_MODE 3 "" "Allegro reference manual"
.SH NAME
.PP
ALLEGRO_DISPLAY_MODE - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

typedef\ struct\ ALLEGRO_DISPLAY_MODE
\f[]
.fi
.SH DESCRIPTION
.PP
Used for display mode queries.
Contains information about a supported fullscreen display mode.
.IP
.nf
\f[C]
typedef\ struct\ ALLEGRO_DISPLAY_MODE\ {
\ \ \ int\ width;\ \ \ \ \ \ \ \ \ \ //\ Screen\ width
\ \ \ int\ height;\ \ \ \ \ \ \ \ \ //\ Screen\ height
\ \ \ int\ format;\ \ \ \ \ \ \ \ \ //\ The\ pixel\ format\ of\ the\ mode
\ \ \ int\ refresh_rate;\ \ \ //\ The\ refresh\ rate\ of\ the\ mode
}\ ALLEGRO_DISPLAY_MODE;
\f[]
.fi
.PP
The \f[C]refresh_rate\f[] may be zero if unknown.
.SH SEE ALSO
.PP
al_get_display_mode(3)
