.TH ALLEGRO_MONITOR_INFO 3 "" "Allegro reference manual"
.SH NAME
.PP
ALLEGRO_MONITOR_INFO - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

typedef\ struct\ ALLEGRO_MONITOR_INFO
\f[]
.fi
.SH DESCRIPTION
.PP
Describes a monitors size and position relative to other monitors.
x1, y1 will be 0, 0 on the primary display.
Other monitors can have negative values if they are to the left or above
the primary display.
.IP
.nf
\f[C]
typedef\ struct\ ALLEGRO_MONITOR_INFO
{
\ \ \ int\ x1;
\ \ \ int\ y1;
\ \ \ int\ x2;
\ \ \ int\ y2;
}\ ALLEGRO_MONITOR_INFO;
\f[]
.fi
.SH SEE ALSO
.PP
al_get_monitor_info(3)
