.TH al_attach_sample_instance_to_voice 3 "" "Allegro reference manual"
.SH NAME
.PP
al_attach_sample_instance_to_voice - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_audio.h>

bool\ al_attach_sample_instance_to_voice(ALLEGRO_SAMPLE_INSTANCE\ *spl,
\ \ \ ALLEGRO_VOICE\ *voice)
\f[]
.fi
.SH DESCRIPTION
.PP
Attaches a sample to a voice, and allows it to play.
The sample\[aq]s volume and loop mode will be ignored, and it must have
the same frequency and depth (including signed-ness) as the voice.
This function may fail if the selected driver doesn\[aq]t support
preloading sample data.
.PP
At this time, we don\[aq]t recommend attaching samples directly to
voices.
Use a mixer in between.
.PP
Returns true on success, false on failure.
.SH SEE ALSO
.PP
al_detach_voice(3)
