.TH al_color_hsl 3 "" "Allegro reference manual"
.SH NAME
.PP
al_color_hsl - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_color.h>

ALLEGRO_COLOR\ al_color_hsl(float\ h,\ float\ s,\ float\ l)
\f[]
.fi
.SH DESCRIPTION
.PP
Return an ALLEGRO_COLOR(3) structure from HSL (hue, saturation,
lightness) values.
.SH SEE ALSO
.PP
al_color_hsl_to_rgb(3), al_color_hsv(3)
