.TH al_color_hsv 3 "" "Allegro reference manual"
.SH NAME
.PP
al_color_hsv - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_color.h>

ALLEGRO_COLOR\ al_color_hsv(float\ h,\ float\ s,\ float\ v)
\f[]
.fi
.SH DESCRIPTION
.PP
Return an ALLEGRO_COLOR(3) structure from HSV (hue, saturation, value)
values.
.SH SEE ALSO
.PP
al_color_hsv_to_rgb(3), al_color_hsl(3)
