.TH al_destroy_bitmap 3 "" "Allegro reference manual"
.SH NAME
.PP
al_destroy_bitmap - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

void\ al_destroy_bitmap(ALLEGRO_BITMAP\ *bitmap)
\f[]
.fi
.SH DESCRIPTION
.PP
Destroys the given bitmap, freeing all resources used by it.
Does nothing if given the null pointer.
.PP
It is an error to destroy a bitmap while it (or a sub-bitmap) are the
target bitmap of any thread.
.SH SEE ALSO
.PP
al_create_bitmap(3)
