.TH al_get_monitor_info 3 "" "Allegro reference manual"
.SH NAME
.PP
al_get_monitor_info - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

bool\ al_get_monitor_info(int\ adapter,\ ALLEGRO_MONITOR_INFO\ *info)
\f[]
.fi
.SH DESCRIPTION
.PP
Get information about a monitor\[aq]s position on the desktop.
adapter is a number from 0 to al_get_num_video_adapters()-1.
.PP
Returns true on success, false on failure.
.SH SEE ALSO
.PP
ALLEGRO_MONITOR_INFO(3), al_get_num_video_adapters(3)
