.TH al_get_errno 3 "" "Allegro reference manual"
.SH NAME
.PP
al_get_errno - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

int\ al_get_errno(void)
\f[]
.fi
.SH DESCRIPTION
.PP
Some Allegro functions will set an error number as well as returning an
error code.
Call this function to retrieve the last error number set for the calling
thread.
