.TH al_get_opengl_texture_size 3 "" "Allegro reference manual"
.SH NAME
.PP
al_get_opengl_texture_size - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_opengl.h>

void\ al_get_opengl_texture_size(ALLEGRO_BITMAP\ *bitmap,\ int\ *w,\ int\ *h)
\f[]
.fi
.SH DESCRIPTION
.PP
Retrieves the size of the texture used for the bitmap.
This can be different from the bitmap size if OpenGL only supports
power-of-two sizes or if it is a sub-bitmap.
0\[aq]s are returned if the bitmap is not an OpenGL bitmap.
