.TH al_get_num_video_adapters 3 "" "Allegro reference manual"
.SH NAME
.PP
al_get_num_video_adapters - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

int\ al_get_num_video_adapters(void)
\f[]
.fi
.SH DESCRIPTION
.PP
Get the number of video "adapters" attached to the computer.
Each video card attached to the computer counts as one or more adapters.
An adapter is thus really a video port that can have a monitor connected
to it.
.SH SEE ALSO
.PP
al_get_monitor_info(3)
