.TH al_ref_buffer 3 "" "Allegro reference manual"
.SH NAME
.PP
al_ref_buffer - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

const\ ALLEGRO_USTR\ *al_ref_buffer(ALLEGRO_USTR_INFO\ *info,\ const\ char\ *s,\ size_t\ size)
\f[]
.fi
.SH DESCRIPTION
.PP
Like al_ref_cstr(3) but the size of the string data is passed in as a
parameter.
Hence you can use it to reference only part of a string or an arbitrary
region of memory.
.PP
The string is valid while the underlying C string is valid.
.SH SEE ALSO
.PP
al_ref_cstr(3), al_ref_ustr(3)
