.TH al_start_timer 3 "" "Allegro reference manual"
.SH NAME
.PP
al_start_timer - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

void\ al_start_timer(ALLEGRO_TIMER\ *timer)
\f[]
.fi
.SH DESCRIPTION
.PP
Start the timer specified.
From then, the timer\[aq]s counter will increment at a constant rate,
and it will begin generating events.
Starting a timer that is already started does nothing.
.SH SEE ALSO
.PP
al_stop_timer(3), al_get_timer_started(3)
