.TH al_toggle_display_flag 3 "" "Allegro reference manual"
.SH NAME
.PP
al_toggle_display_flag - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

bool\ al_toggle_display_flag(ALLEGRO_DISPLAY\ *display,\ int\ flag,\ bool\ onoff)
\f[]
.fi
.SH DESCRIPTION
.PP
Deprecated synonym for al_set_display_flag(3).
