.TH al_ustr_dup_substr 3 "" "Allegro reference manual"
.SH NAME
.PP
al_ustr_dup_substr - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro.h>

ALLEGRO_USTR\ *al_ustr_dup_substr(const\ ALLEGRO_USTR\ *us,\ int\ start_pos,
\ \ \ int\ end_pos)
\f[]
.fi
.SH DESCRIPTION
.PP
Return a new copy of a string, containing its contents in the byte
interval [start_pos, end_pos).
The new string will be NUL terminated and will need to be freed with
al_ustr_free(3).
.PP
If you need a range of code-points instead of bytes, use
al_ustr_offset(3) to find the byte offsets.
.SH SEE ALSO
.PP
al_ustr_dup(3)
