.TH ALLEGRO_PRIM_QUALITY 3 "" "Allegro reference manual"
.SH NAME
.PP
ALLEGRO_PRIM_QUALITY - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_primitives.h>

#define\ ALLEGRO_PRIM_QUALITY\ 10
\f[]
.fi
.SH DESCRIPTION
.PP
Defines the quality of the quadratic primitives.
At 10, this roughly corresponds to error of less than half of a pixel.
