.TH ALLEGRO_PRIM_STORAGE 3 "" "Allegro reference manual"
.SH NAME
.PP
ALLEGRO_PRIM_STORAGE - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_primitives.h>

typedef\ enum\ ALLEGRO_PRIM_STORAGE
\f[]
.fi
.SH DESCRIPTION
.PP
Enumerates the types of storage an attribute of a custom vertex may be
stored in.
.IP \[bu] 2
ALLEGRO_PRIM_FLOAT_2 - A doublet of floats
.IP \[bu] 2
ALLEGRO_PRIM_FLOAT_3 - A triplet of floats
.IP \[bu] 2
ALLEGRO_PRIM_SHORT_2 - A doublet of shorts
.SH SEE ALSO
.PP
ALLEGRO_PRIM_ATTR(3)
