.TH ALLEGRO_AUDIO_PAN_NONE 3 "" "Allegro reference manual"
.SH NAME
.PP
ALLEGRO_AUDIO_PAN_NONE - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_audio.h>

#define\ ALLEGRO_AUDIO_PAN_NONE\ \ \ \ \ \ (-1000.0f)
\f[]
.fi
.SH DESCRIPTION
.PP
Special value for the ALLEGRO_AUDIOPROP_PAN property.
Use this value to play samples at their original volume with panning
disabled.
