.TH ALLEGRO_MIXER 3 "" "Allegro reference manual"
.SH NAME
.PP
ALLEGRO_MIXER - Allegro 5 API
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_audio.h>

typedef\ struct\ ALLEGRO_MIXER\ ALLEGRO_MIXER;
\f[]
.fi
.SH DESCRIPTION
.PP
A mixer is a type of stream which mixes together attached streams into a
single buffer.
